name: Gen documentation

on:
  push:
    branches: [main]
    paths: ["**.ts", ".github/workflows/docs.yml"]
  pull_request:
    branches: [main]
    paths: ["**.ts", ".github/workflows/docs.yml"]

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=npm depName=typedoc
      typedoc_version: 0.28.2
    steps:
      - uses: actions/checkout@v4

      - name: Build documentation with TypeDoc
        run: >
          npx typedoc@$typedoc_version --readme none --disableSources
          --includeVersion --exclude "src/mockdata/*" --out public src

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
